# -*- coding: utf-8 -*-
"""
FastAPI Router for Analysis Jobs and Analysis Results.
Implements:
- GET /api/analysis (list user's analysis jobs)
- GET /api/analysis/{analysis_id} (fetch job status & details)
- GET /api/analysis/{analysis_id}/results (fetch empirical analysis results)
"""

import uuid
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from sqlalchemy import desc

from backend.database.connection import get_db
from backend.database.models import User, AnalysisJob, AnalysisResult
from backend.database.schemas import AnalysisJobResponse, AnalysisResultResponse
from backend.database.repositories import AnalysisRepository, DatasetRepository
from backend.authentication.jwt_handler import get_current_active_user

router = APIRouter(prefix="/api/analysis", tags=["Analysis"])


@router.get("", response_model=List[AnalysisJobResponse])
def list_analysis_jobs(
    dataset_id: Optional[str] = None,
    skip: int = 0,
    limit: int = 50,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """Lists analysis jobs initiated by the caller (or all if admin)."""
    is_admin = current_user.role.lower() == "admin"
    query = db.query(AnalysisJob)
    if not is_admin:
        query = query.filter(AnalysisJob.user_id == current_user.id)
    if dataset_id:
        try:
            did = uuid.UUID(dataset_id)
            query = query.filter(AnalysisJob.dataset_id == did)
        except ValueError:
            pass

    jobs = query.order_by(desc(AnalysisJob.started_at)).offset(skip).limit(limit).all()
    return [
        AnalysisJobResponse(
            id=str(j.id),
            dataset_id=str(j.dataset_id),
            user_id=str(j.user_id),
            job_type=j.job_type,
            status=j.status,
            started_at=j.started_at.isoformat() if j.started_at else None,
            completed_at=j.completed_at.isoformat() if j.completed_at else None,
            error_message=j.error_message,
            result_location=j.result_location
        )
        for j in jobs
    ]


@router.get("/{analysis_id}", response_model=AnalysisJobResponse)
def get_analysis_job(
    analysis_id: str,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """Retrieves status and details of an analysis job."""
    try:
        jid = uuid.UUID(analysis_id)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid analysis job UUID.")

    job = AnalysisRepository.get_job(db, jid)
    if not job:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Analysis job not found.")

    is_owner = str(job.user_id) == str(current_user.id)
    is_admin = current_user.role.lower() == "admin"
    if not is_owner and not is_admin:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access denied to this analysis job.")

    return AnalysisJobResponse(
        id=str(job.id),
        dataset_id=str(job.dataset_id),
        user_id=str(job.user_id),
        job_type=job.job_type,
        status=job.status,
        started_at=job.started_at.isoformat() if job.started_at else None,
        completed_at=job.completed_at.isoformat() if job.completed_at else None,
        error_message=job.error_message,
        result_location=job.result_location
    )


@router.get("/{analysis_id}/results", response_model=List[AnalysisResultResponse])
def get_analysis_results(
    analysis_id: str,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """Fetches the empirical results generated by this analysis job."""
    try:
        jid = uuid.UUID(analysis_id)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid analysis job UUID.")

    job = AnalysisRepository.get_job(db, jid)
    if not job:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Analysis job not found.")

    is_owner = str(job.user_id) == str(current_user.id)
    is_admin = current_user.role.lower() == "admin"
    if not is_owner and not is_admin:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access denied to this analysis job.")

    results = AnalysisRepository.get_results_by_job(db, jid)
    return [
        AnalysisResultResponse(
            id=str(r.id),
            job_id=str(r.job_id),
            dataset_id=str(r.dataset_id),
            result_type=r.result_type,
            result_data=r.result_data,
            created_at=r.created_at.isoformat() if r.created_at else None
        )
        for r in results
    ]
